# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None)),
                ('tpl_type', models.IntegerField(default=None)),
                ('info', models.TextField(default=None)),
            ],
        ),
    ]
